config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title X-editable
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :body

  .form-actions
    = f.button :submit

    = link_to 'Все посты', posts_path, class: 'btn btn-default'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.page-header
  %h2
    Посты
    = link_to 'Добавить', new_post_path, class: 'btn btn-success btn-sm'

%table.table.table-stripped.table-bordered

  %thead
    %tr
      %th Заголовок
      %th Текст
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.body
        %td= link_to 'Показать', post
        %td= link_to 'Удалить', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/posts/new.html.haml
%h1 Новый пост

= render 'form'

app/views/posts/show.html.haml
- default_hesh_xeditable = { "data-model" => "post", "data-pk" => @post.id, "data-title" => "Введите новое значение", "data-url" => post_url(@post),"data-xeditable" => "true", :href => "#" }

%br
%br
%br
%br
%br

%p
  %strong Заголовок:
  %a.editable{ default_hesh_xeditable, "data-name" => "title" }
    = @post.title
%p
  %strong Текст:
  %a.editable{ default_hesh_xeditable, "data-name" => "body" }
    = @post.body
%p
  %button#editable_on_of.btn.btn-default Редактор (вкл/выкл)
  = link_to 'Все посты', posts_path, class: 'btn btn-default'